services:
  db:
    image: postgres:14.8-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5434:5432"

  redis_service:
    image: redis:8.4-alpine
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server